name: Deploy pipeline DEV

on:
  push:
    branches: [develop]
    paths-ignore:
      - '.github/**'
  pull_request:
    branches: [develop]
    types: [closed]
    paths-ignore:
      - '.github/**'
      
permissions:
  id-token: write
  contents: write

jobs:
  build_and_deploy:
    uses: rhawan/github-actions-workflows/.github/workflows/argo-develop.yaml@develop
    secrets: inherit
    with:
      app_name: "order-manager"
      namespace: "develop-order-manager"